COMMENT ON TABLE `shop` IS '商铺表';
COMMENT ON TABLE `shop_item_group` IS '商品分组表';
COMMENT ON TABLE `shop_item` IS '商品表';
COMMENT ON TABLE `shop_contract` IS '小铺合同表';
COMMENT ON TABLE `shop_contract_file` IS '小铺合同文件表';
COMMENT ON TABLE `shop_item_contract` IS '商品合同绑定表';
COMMENT ON TABLE `shop_contract_signature` IS '合同签署留痕表';
COMMENT ON TABLE `shop_order` IS '订单表';
COMMENT ON TABLE `shop_transaction` IS '交易流水表';
