server:
  port: ${FLYFISH_SHOP_PORT:10082}

spring:
  config:
    import:
      - classpath:/config/flyfish-common.yml
      - classpath:/config/flyfish-platform.yml
      - classpath:/config/flyfish-auth.yml
      - classpath:/config/flyfish-git.yml
      - classpath:/config/flyfish-shop.yml
  profiles:
    active: @profiles.active@
